version: "3"

services:
  # Central Pkarr relay / Data Store / Indexer / Aggregator / etc. All in one.
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile.backend
    volumes: 
      - ./skunk-works:/usr/src/app
      - backend_storage:/usr/src/app/.storage
    environment:
      - TESTNET=true
      - PUBKY_SERVER_SECRET=${PUBKY_SERVER_SECRET} # Create your own app.pkarr.org
      - PUBKY_SERVER_DOMAIN= # Leave empty if TESTNET=true
    command: [npm, run, backend:dev]
    networks:
      - default
    ports:
      - 7258:7258
      - 7259:7259
  backend-app:
    build:
      context: ./
      dockerfile: ./0_backend/Dockerfile
    ports:
      - 4242:4242
      - 4241:4241
    env_file:
      - ./0_backend/.env
    volumes:
      - ./:/app
    restart: always

  frontend:
    build:
      context: ./
      dockerfile: ./1_frontend/Dockerfile
    ports:
      - 3004:3004
    volumes:
      - ./:/app
    restart: always

volumes:
 backend_storage:

networks:
  default:
    driver: bridge