version: "3"

services:

  backend-app:
    build:
      context: ./0_backend
      dockerfile: ./Dockerfile
    ports:
      - 4242:4242
    env_file:
      - ./0_backend/.env
    volumes:
      - ./0_backend/skunk-works:/skunk-works
      - ./0_backend:/usr/src/app
      - ./0_backend/data:/usr/src/app/data
    restart: always

  frontend:
    build:
      context: ./1_frontend
      dockerfile: ./Dockerfile
    ports:
      - 3004:3000
    volumes:
      - ./1_frontend:/usr/src/app
    restart: always
    depends_on:
      - backend-app